### PR TITLE
error trap & test for stopped daemon

### LINKED ISSUE #48: Uncaught Error: connect ECONNREFUSED
Happens when trying to use ipfs-api on a stopped daemon. In the browser, with ipfsapi.min.js, it is "Uncaught (in promise) TypeError: Failed to fetch"

Would be nice to trap this so I can prompt user to check their ipfs connection

### PR DESCRIPTION
**Pull request by ckeenan**
This should resolve #48

### CODE REVIEW

File: src/request-api.js [hunk 1]
```diff
@@ -90,6 +90,10 @@ function requestAPI (path, args, opts, files, buffer, cb) {
     })
   })
 
+  req.on('error', function (err) {
+    return cb(err, null)
+  })
```
Comment (jbenet) [inline src/request-api.js]: ahh yep. :+1: 

is it guaranteed that `http.request` only calls _either_ the callback (i.e. emits `response`) or emits `error` ? (i believe so, but asking others). cc @diasdavid

File: test/test.js [hunk 2]
```diff
@@ -25,12 +25,13 @@ describe('ipfs node api', function () {
...
       log('ipfs init done')
+      ipfsNode = node
 
-      node.startDaemon(function (err, ignore) {
+      ipfsNode.startDaemon(function (err, ignore) {
         if (err) throw err
         log('ipfs daemon running')
 
-        ipfs = ipfsApi(node.apiAddr)
+        ipfs = ipfsApi(ipfsNode.apiAddr)
```
Comment (jbenet) [inline test/test.js]: are these changes necessary? or just for readability? 

maybe i'm not seeing the js-scoping issue at hand, but afaict it is fine to do as it was?

File: test/test.js [hunk 3]
```diff
@@ -285,4 +286,18 @@ describe('ipfs node api', function () {
...
+    ipfsNode.stopDaemon(function () {
+      if (!nodeStopped) {
+        nodeStopped = true
+        ipfs.id(function (err, res) {
+          assert.equal(err.code, 'ECONNREFUSED')
+          done()
+        })
+      }
+    })
+  })
```
Comment (jbenet) [inline test/test.js]: :+1:

File: src/request-api.js (hunk 1 above)
Comment (diasdavid) [inline src/request-api.js]: Following https://nodejs.org/api/http.html#http_http_request_options_callback, an error is only emitted if something with the `request` goes wrong and the callback is only called if we get a response (after the request went well). So, yeah, all good :) 

```
If any error is encountered during the request (be that with DNS resolution, TCP level errors, or actual HTTP parse errors) an 'error' event is emitted on the returned request object.
```

File: test/test.js (hunk 2 above)
Comment (ckeenan) [inline test/test.js]: Wanted a reference to the node so I could stop the daemon and check for the error in the last test. I can revert back to using `node.*` instead of `ipfsNode.*` for this before() block.. I thought it was more readable to stick with one variable name

Comment (jbenet) [inline test/test.js]: Ohh nevermind that makes sense. i hadn't connected them

**Comment by jbenet** [comment]
This LGTM. :+1:  thanks for the PR @ckeenan

**Comment by jbenet** [comment]
Published v2.2.1
